name: ppkd_b7
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  shimmer_animation: ^2.2.2+1
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Perbaikan struktur utama Flutter di bawah ini
flutter:
  uses-material-design: true

  # Jika Anda memiliki folder aset, aktifkan baris di bawah ini:
  assets:
    - assets/fonts/
    - assets/image/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.otf
          weight: 700
        - asset: assets/fonts/Gilroy-Light.otf
